.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XMMS-SHELL SECTION "February  8, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xmms-shell \- Command-line utility for controlling XMMS externally
.SH SYNOPSIS
.B xmms-shell [OPTIONS]
.SH OPTIONS
.TP
.B \-e [expr], \-\-eval [expr]
Evaluate expr and exit
.TP
.B \-h, \-\-help
Display this message and exit
.TP
.B \-n [s], \-\-session [s]
Specify session ID
Show version of program.
.SH SEE ALSO
.BR xmms (1)
.SH AUTHOR
XMMS-Shell and this manual page were written by Logan Hanks <logan@vt.edu>.

