######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 9 10:10:41 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . include src
INCLUDEPATH += . include /usr/include/xmms/
LIBS += -lxmms
QMAKE_CXXFLAGS += $$system(pkg-config --cflags glib)

# Input
HEADERS += include/command.h \
           include/eval.h \
           include/exception.h \
           include/formatter.h \
           include/general.h \
           include/getline.h \
           include/misc.h \
           include/output.h \
           include/playback.h \
           include/playlist.h \
           include/script.h \
           include/session.h \
           include/util.h \
           include/volume.h \
           include/window.h
SOURCES += src/command.cc \
           src/eval.cc \
           src/exception.cc \
           src/formatter.cc \
           src/general.cc \
           src/getline.cc \
           src/misc.cc \
           src/output.cc \
           src/playback.cc \
           src/playlist.cc \
           src/script.cc \
           src/session.cc \
           src/util.cc \
           src/volume.cc \
           src/window.cc \
           src/xmms-shell.cc
unix {
    MOC_DIR=.moc
    UI_DIR=.ui
    OBJECTS_DIR=.obj
} else {
    MOC_DIR=tmp/moc
    UI_DIR=tmp/ui
    OBJECTS_DIR=tmp/obj
}
